import {ClerkProvider} from '@clerk/nextjs'
import {Inter} from 'next/font/google'

const inter = Inter({subsets: ['latin']})

export const metadata = {
	title: 'Clicking',
	description: 'Generated by create next app',
}

export default function b1Layout({children}: {children: React.ReactNode}) {
	return (
		<ClerkProvider>
			<section>{children}</section>
		</ClerkProvider>
	)
}
