import './globals.css'
import {Inter} from 'next/font/google'
import {ClerkProvider, SignedIn, SignedOut} from '@clerk/nextjs'

const inter = Inter({subsets: ['latin']})

export const metadata = {
	title: 'Babeular',
	description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
	return (
		<ClerkProvider>
			<SignedIn>
				<html lang="en">
					<body className={inter.className}>{children}</body>
				</html>
			</SignedIn>
		</ClerkProvider>
	)
}
