import { WagmiConfig, createConfig, mainnet } from 'wagmi'
import './globals.css'
import { Inter } from 'next/font/google'
import { createPublicClient, http } from 'viem'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const config = createConfig({
  autoConnect: true,
  publicClient: createPublicClient({
    chain: mainnet,
    transport: http(),
  }),
})


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <WagmiConfig config={undefined}>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </WagmiConfig>
  )
}
function publicProvider() {
  throw new Error('Function not implemented.')
}

