import {ClerkProvider} from '@clerk/nextjs'
import './globals.css'
import {Inter} from 'next/font/google'

const inter = Inter({subsets: ['latin']})

export const metadata = {
	title: 'Clerk Test',
	description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
	return (
		<html lang="en">
			<ClerkProvider>
				<body className={inter.className}>{children}</body>
			</ClerkProvider>
		</html>
	)
}
